Catch AttributeError exception on user reactions iterator
It seems that sometimes the guild is a simple object file, and doesnt have get_member

File "/home/user/.envs/discord/lib/python3.6/site-packages/discord/iterators.py", line 166, in fill_users
    member = self.guild.get_member(member_id)
AttributeError: 'Object' object has no attribute 'get_member'

Add generic try/except to catch this case, and set member to zero.

Tested in my app and fixes issue